name: phenorag-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - streamlit=1.34.1
  - pandas=2.2.2
  - numpy=1.26.4
  - openai=1.30.1
  - python-dotenv=1.0.1
  # Conda can handle PyTorch and FAISS installation robustly
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - faiss-cpu
  - pip:
    - sentence-transformers==2.7.0